# Generated by Django 5.2.7 on 2025-10-08 22:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('equipe', models.CharField(choices=[('E1', 'Equipe 1'), ('E2', 'Equipe 2'), ('E3', 'Equipe 3'), ('E4', 'Equipe 4')], max_length=2, verbose_name='Equipe')),
                ('data_base_plantao', models.DateField(default=datetime.date.today, verbose_name='Data Base do Plantão')),
                ('data_ultima_ferias_anual', models.DateField(blank=True, null=True, verbose_name='Últimas Férias Anuais')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['equipe', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AT', 'Atestado (Afastamento por Saúde)'), ('FA', 'Falta (Não Justificada)'), ('FE', 'Férias (21 Plantões)'), ('FT', 'Férias (Anual)')], max_length=2)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Descrição/Observações')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='servidores.servidor')),
            ],
            options={
                'verbose_name': 'Afastamento/Registro de Falta',
                'verbose_name_plural': 'Afastamentos/Registros de Falta',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
