# Generated by Django 5.2.7 on 2025-10-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='servidores_fotos/', verbose_name='Foto do Servidor'),
        ),
    ]
