# Generated by Django 5.2.7 on 2025-10-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_alter_servidor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='data_ferias_21_plantoes',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início Última Férias 21'),
        ),
    ]
