# Generated by Django 5.2.7 on 2025-10-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0004_servidor_data_ferias_21_plantoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='data_ultima_ferias_anual',
        ),
        migrations.AddField(
            model_name='servidor',
            name='data_ultima_ferias_anual_base',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Última Férias Anual'),
        ),
    ]
