# Generated by Django 5.2.7 on 2025-11-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0005_remove_servidor_data_ultima_ferias_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='preferencia_ferias_1',
            field=models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, null=True, verbose_name='1ª Preferência (Mês)'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='preferencia_ferias_2',
            field=models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, null=True, verbose_name='2ª Preferência (Mês)'),
        ),
    ]
