# Generated by Django 5.2.7 on 2025-11-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0006_servidor_preferencia_ferias_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='horas_extras_acumuladas',
            field=models.FloatField(default=0.0, verbose_name='Banco de Horas Extras Acumuladas'),
        ),
    ]
